#====================#
#Autographs V${VERSION}
#Created by: Netpex
#================#

#Options:
options:
  prefix: "&7[&x&0&8&4&c&f&bA&x&1&a&5&f&f&bu&x&2&d&7&1&f&bt&x&3&f&8&4&f&co&x&5&1&9&6&f&cg&x&6&4&a&9&f&cr&x&7&6&b&b&f&ca&x&8&8&c&e&f&dp&x&9&b&e&0&f&dh&x&a&d&f&3&f&ds&7]&r"
  #Prefix created using https://rgb.birdflop.com
  forceItemSlot: false
  useHeadDataBase: true
  responses:
    still-dressed: "%prefix% &fYou are still dressed as %charcter%&f!"
    signed: "%prefix% &fCongrats!  %charcter% &fsigned your %prefix% &bBook&f!"
    already-signed: "%prefix% &fHey!  %charcter% &fhas already signed your %prefix% &bBook&f!"


#Autograph Item
item:
  name: "&a&lAutograph Book"
  item: "BOOK"
  model-data: 1 #If you aren't sure what this means don't change it.
  force-slot: 1
  lore:
    - "&fYour personal autograph book."
    - ""
    - "&a&lClick&f a character to collect"
    - "&ftheir autograph!"
    - ""
    - "&a&lClick&f anywhere to open your book!"

worlds:
  mk:
    title: "&6Magic &9Kingdom"
    model-data: 1
    item: "ENDER_PEARL"
    lore:
      - "Welcome to Magic kingdom"
    gui-position:
      x: 5
      y: 1

costumes:
  mickeymouse:
    name: "&c&lMickey Mouse"
    helmet: "13693" #If you arent using head-database set this to a color.
    chestplate: "Red"
    leggings: "Black"
    boots: "Yellow"
    park: "mk" #Must be registered about
    gui-item: "13693" #If you arent using head-database set this to a itemstack.
    lore:
      - "&fYour pal, Mickey Mouse!"

gui:
  costumes:
    custom-frame: true #If you aren't sure what this means make it false.
    item: "IRON_INGOT"
    gui-position:
      x: 4
      y: 5
    model-data: 1
    right-arrow:
      item: "IRON_INGOT"
      gui-position:
        x: 7
        y: 5
      model-data: 2
      title: "&6BACK"
      lore:
        - "&6Click &7to go &5back &7a &9page."
    left-arrow:
      item: "IRON_INGOT"
      gui-position:
        x: 8
        y: 5
      model-data: 3
      title: "&8NEXT"
      lore:
        - "&6Click &7to see the &2next &9page."
    back-arrow:
      item: "IRON_INGOT"
      gui-position:
        x: 0
        y: 5
      model-data: 4
      title: "&5EXIT"
      lore:
        - "&6Click &7to &4Exit&7."
  color-selector:
    custom-frame: true #If you aren't sure what this means make it false.
    item: "IRON_INGOT"
    gui-position:
      x: 0
      y: 0
    model-data: 5
    focus-item:
      gui-position:
        x: 4
        y: 0
    back-arrow:
      item: "IRON_INGOT"
      gui-position:
        x: 0
        y: 1
      model-data: 4
      title: "&6Return"
      lore:
        - "&6Click &7to &4Exit&7/&2Save&7."