#====================#
#Autographs V${VERSION}
#Created by: Netpex
#================#

#Options:
options:
  prefix: "&7[&x&0&8&4&c&f&bA&x&1&a&5&f&f&bu&x&2&d&7&1&f&bt&x&3&f&8&4&f&co&x&5&1&9&6&f&cg&x&6&4&a&9&f&cr&x&7&6&b&b&f&ca&x&8&8&c&e&f&dp&x&9&b&e&0&f&dh&x&a&d&f&3&f&ds&7]&r"
  #Prefix created using https://rgb.birdflop.com
  forceItemSlot: false
  useHeadDataBase: true
  responses:
    still-dressed: "%prefix% &fYou are still dressed as %charcter%&f!"
    signed: "%prefix% &fCongrats!  %charcter% &fsigned your %prefix% &bBook&f!"
    already-signed: "%prefix% &fHey!  %charcter% &fhas already signed your %prefix% &bBook&f!"


#Autograph Item
item:
  name: "&a&lAutograph Book"
  item: "BOOK"
  model-data: 1 #If you aren't sure what this means don't change it.
  force-slot: 1
  lore:
    - "&fYour personal autograph book."
    - ""
    - "&a&lClick&f a character to collect"
    - "&ftheir autograph!"
    - ""
    - "&a&lClick&f anywhere to open your book!"

contumes:
  mickeymouse:
    name: "&c&lMickey Mouse"
    helmet: "13693"
    chestplate: "Red"
    leggings: "Black"
    boots: "Yellow"
    lore:
      - "&fYour pal, Mickey Mouse!"

gui:
  costumes:
    custom-frame: true #If you aren't sure what this means make it false.
    item: "IRON_INGOT"
    x: 4
    y: 5
    custom-data: 1
    right-arrow:
      item: "IRON_INGOT"
      x: 7
      y: 5
      custom-data: 2
      title: "&6BACK"
      lore:
        - "Click to go back a page."
    left-arrow:
      item: "IRON_INGOT"
      x: 8
      y: 5
      custom-data: 3
      title: "&8NEXT"
      lore:
        - "Click to see the next page."
    back-arrow:
      item: "IRON_INGOT"
      x: 0
      y: 5
      custom-data: 4
      title: "&5EXIT"
      lore:
        - "Click to exit."